export const INITIALIZE_TRANSACTIONS = 'INITIALIZE_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS';

export const INITIALIZE_MANUAL_TRANSACTIONS = 'INITIALIZE_MANUAL_TRANSACTIONS';
export const ADD_MANUAL_TRANSACTION = 'ADD_MANUAL_TRANSACTION';
export const UPDATE_MANUAL_TRANSACTIONS = 'UPDATE_MANUAL_TRANSACTIONS';

export const INITIALIZE_TOKEN_INFO = 'INITIALIZE_TOKEN_INFO';
export const UPDATE_TOKEN_INFO = 'UPDATE_TOKEN_INFO';

export const INITIALIZE_ICO_INFO = 'INITIALIZE_ICO_INFO';
export const UPDATE_ICO_INFO = 'UPDATE_ICO_INFO';

export const INITIALIZE_INVESTOR_INFO = 'INITIALIZE_INVESTOR_INFO';
export const UPDATE_INVESTOR_INFO = 'UPDATE_INVESTOR_INFO';

export const INITIALIZE_INVESTOR_TRANSACTIONS = 'INITIALIZE_INVESTOR_TRANSACTIONS';
export const UPDATE_INVESTOR_TRANSACTIONS_ICO = 'UPDATE_INVESTOR_TRANSACTIONS_ICO';
export const UPDATE_INVESTOR_TRANSACTIONS_PRE_ICO = 'UPDATE_INVESTOR_TRANSACTIONS_PRE_ICO';
